ffmpeg:
  build: .
  devices:
    - /dev/nvidia-uvm:/dev/nvidia-uvm
    - /dev/nvidia0:/dev/nvidia0
    - /dev/nvidiactl:/dev/nvidiactl
  container_name: ffmpeg
  volumes:
    - /usr/lib64/nvidia:/usr/local/nvidia/lib64
    - /var/lib/chinachu/recorded:/var/lib/videos
